name: Gestao de Vagas Application


on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
      
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: 17
          
            - name: Build project
              run: mvn clean install
            
            - name: Login docker
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}
            
            - name: Build docker image
              run: docker build -t brenoborges/gestao_vagas .
        
            - name: Publish image
              run: docker push brenoborges/gestao_vagas
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image docker hub
              run: docker pull brenoborges/gestao_vagas:latest
            
            - name: remove container
              run: docker rm -f gestao-vagas

            - name: Run docker container
              run: docker run -d -p 8080:8080 -e DATABASE_URL=${{secrets.DATABASE_URL}} -e DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} --name gestao-vagas brenoborges/gestao_vagas